spring:
  application:
    name: langchain-java

langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-3.5-turbo
      temperature: 0.7
      log-requests: true
      log-responses: true

logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG
